Vagrant.configure("2") do |config|
  
  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = "node#{i}"
      node.vm.box = "generic/debian10"
      node.vm.network "private_network", ip: "192.168.33.7#{i}"

      node.vm.provider "virtualbox" do |vb|
        vb.name = "node#{i}"
        vb.gui = false
        vb.memory = "512"
      end
  
      #node.vm.provision "shell", path: "deployMySQL1#{i}.sh", privileged: false
    end
  end

  config.vm.define "proxy" do |proxy|
    proxy.vm.hostname = "proxy"
    proxy.vm.box = "generic/debian10"
    proxy.vm.network "private_network", ip: "192.168.16.70"
    
    proxy.vm.provider "virtualbox" do |vb|
      vb.name = "proxy"
      vb.gui = false
      vb.memory = "512"
    end

    #proxy.vm.provision "shell", path: "deployProxySQL.sh", privileged: false
  end

  config.vm.define "hosting" do |hosting|
    hosting.vm.hostname = "hosting"
    hosting.vm.box = "generic/debian10"
    hosting.vm.network "private_network", ip: "192.168.16.69"
    
    hosting.vm.provider "virtualbox" do |vb|
      vb.name = "hosting"
      vb.gui = false
      vb.memory = "512"
    end

    #proxy.vm.provision "shell", path: "deployProxySQL.sh", privileged: false
  end

end

# -*- mode: ruby -*-
# vim: set ft=ruby :
